#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if ! command -v stow >/dev/null 2>&1; then
    echo "Error: 'stow' is not installed"
    exit 1
fi

mkdir -p ~/.config
stow -t ~/.config -d \
    "$SCRIPT_DIR/config" \
    starship/
